name: CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'

      - name: Go path
        run: |
            @echo "GO ENV"
            GOPATH=${GOPATH} ${GO} env
            @echo ${GO} version
            @echo    

      - name: IAC End to End Test
        run: go test
        
      - name: IaC Static Code Analysis
        uses: bridgecrewio/checkov-action@v5
