name: CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'

      - name: Setup AWS Credentials
        run: |
          # Setup the credentials in the workspace because everything in terraform is
          # driven off profiles
          mkdir -p .aws
          echo "[default]" > .aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}" >> .aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}" >> .aws/credentials
          
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1  

      - name: IAC End to End Test
        run: |
          cd test 
          go test -v -timeout 10m
        env:
          AWS_PROFILE: default  
          AWS_SHARED_CREDENTIALS_FILE: .aws/credentials
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        
      - name: IaC Static Code Analysis
        uses: bridgecrewio/checkov-action@v5
