name: CI
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code

      - name: IaC Static Code Analysis
        uses: bridgecrewio/checkov-action@v5

      - name: IaC Unit Test
